# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-12-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_mineral'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='group',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
